version: '3.1'

services:
  api:
    restart: always
    container_name: api
    command: "npm run start:dev"
    build:
      context: ./
      target: dev-bind
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/khalil/pictures:/home/pictures
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - adminer
  psql-db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - 6379
    networks:
      - app-network
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - psql-db

networks:
  app-network:


volumes:
  db-volume:
  redis-volume:
